[workspace]
members = ["crates/blue-lang-syntax", "crates/blue-lang-fmt", "crates/blue-lang-waku", "crates/blue-lang-check", "crates/blue-lang-bidama"]
resolver = "2"

[workspace.package]
version = "0.0.1"
edition = "2021"
rust-version = "1.89.0"
authors = ["Pleme.io <engineering@pleme.io>"]
license = "MIT"
repository = "https://github.com/pleme-io/blue"
readme = "README.md"

[workspace.dependencies]
blue-lang-syntax = { path = "crates/blue-lang-syntax" }
blue-lang-waku = { path = "crates/blue-lang-waku" }
tatara-lisp = { path = "../tatara-lisp/tatara-lisp" }
tatara-lisp-eval = { path = "../tatara-lisp/tatara-lisp-eval" }
