[package]
name = "blue-lang-pkg"
description = "blue's package manager: the Bluefile surface and its version solver."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
blue-lang-runtime = { workspace = true }
blue-lang-syntax = { workspace = true }
blue-lang-waku = { workspace = true }
blue-lang-bidama = { workspace = true }
tatara-lisp = { workspace = true }
tatara-lisp-eval = { workspace = true }
thiserror = { workspace = true }
