[package]
name = "blue-lang-cli"
description = "The blue command line: run, fmt, ast, erase, check."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "blue"
path = "src/main.rs"

[dependencies]
blue-lang-runtime = { workspace = true }
blue-lang-syntax = { workspace = true }
blue-lang-fmt = { workspace = true }
blue-lang-check = { workspace = true }
blue-lang-test = { workspace = true }
blue-lang-pkg = { workspace = true }
blue-lang-lsp = { workspace = true }
blue-lang-art = { workspace = true }
katsuji = { git = "https://github.com/pleme-io/katsuji", branch = "main" }
blue-lang-waku = { workspace = true }
tatara-lisp-eval = { workspace = true }
clap = { workspace = true }
thiserror = { workspace = true }
