; العربية — one surface over blue's invariant structure.
(defyakugo "ar" "العربية")
(locales "ar")
(words
  ("إذا" if)
  ("مالم" unless)
  ("وإلا_إذا" elsif)
  ("وإلا" else)
  ("نهاية" end)
  ("عرف" def)
  ("ماكرو" defmacro)
  ("اقتبس" quote)
  ("الغ_الاقتباس" unquote)
  ("الغ_ونشر" unquote_splice)
  ("اختبار" test)
  ("اكد" assert)
  ("دالة" fn)
  ("حالة" case)
  ("عندما" when)
  ("نفذ" do)
  ("صحيح" true)
  ("خطا" false)
  ("عدم" nil)
  ("استخدم" use)
  )
