; Deutsch — one surface over blue's invariant structure.
(defyakugo "de" "Deutsch")
(locales "de")
(words
  ("wenn" if)
  ("ausser_wenn" unless)
  ("sonst_wenn" elsif)
  ("sonst" else)
  ("ende" end)
  ("definiere" def)
  ("makro" defmacro)
  ("zitat" quote)
  ("entzitat" unquote)
  ("entzitat_spleiss" unquote_splice)
  ("pruefung" test)
  ("behaupte" assert)
  ("funktion" fn)
  ("fall" case)
  ("bei" when)
  ("tue" do)
  ("wahr" true)
  ("falsch" false)
  ("nichts" nil)
  ("nutze" use)
  )
