; español — one surface over blue's invariant structure.
(defyakugo "es" "español")
(locales "es")
(words
  ("si" if)
  ("a_menos_que" unless)
  ("sino_si" elsif)
  ("sino" else)
  ("fin" end)
  ("definir" def)
  ("macro" defmacro)
  ("citar" quote)
  ("descitar" unquote)
  ("descitar_esparcir" unquote_splice)
  ("prueba" test)
  ("afirmar" assert)
  ("funcion" fn)
  ("caso" case)
  ("cuando" when)
  ("hacer" do)
  ("verdadero" true)
  ("falso" false)
  ("nulo" nil)
  ("usar" use)
  )
