; français — one surface over blue's invariant structure.
(defyakugo "fr" "français")
(locales "fr")
(words
  ("si" if)
  ("sauf_si" unless)
  ("sinon_si" elsif)
  ("sinon" else)
  ("fin" end)
  ("définir" def)
  ("macro" defmacro)
  ("citer" quote)
  ("déciter" unquote)
  ("déciter_étaler" unquote_splice)
  ("essai" test)
  ("affirmer" assert)
  ("fonction" fn)
  ("cas" case)
  ("quand" when)
  ("faire" do)
  ("vrai" true)
  ("faux" false)
  ("néant" nil)
  ("utiliser" use)
  )
