; हिन्दी — one surface over blue's invariant structure.
(defyakugo "hi" "हिन्दी")
(locales "hi")
(words
  ("यदि" if)
  ("जबतकनहीं" unless)
  ("अन्यथायदि" elsif)
  ("अन्यथा" else)
  ("अंत" end)
  ("परिभाषित" def)
  ("मैक्रो" defmacro)
  ("उद्धरण" quote)
  ("अनुद्धरण" unquote)
  ("अनुद्धरणविस्तार" unquote_splice)
  ("परीक्षण" test)
  ("दावा" assert)
  ("फलन" fn)
  ("स्थिति" case)
  ("जब" when)
  ("करो" do)
  ("सत्य" true)
  ("असत्य" false)
  ("शून्य" nil)
  ("उपयोग" use)
  )
