; 日本語 — one surface over blue's invariant structure.
(defyakugo "ja" "日本語")
(locales "ja")
(words
  ("もし" if)
  ("でなければ" unless)
  ("またはもし" elsif)
  ("それ以外" else)
  ("終わり" end)
  ("定義" def)
  ("マクロ定義" defmacro)
  ("引用" quote)
  ("引用解除" unquote)
  ("引用展開" unquote_splice)
  ("試験" test)
  ("検証" assert)
  ("関数" fn)
  ("場合" case)
  ("のとき" when)
  ("実行" do)
  ("真" true)
  ("偽" false)
  ("無" nil)
  ("使用" use)
  )
