; symbolic — one surface over blue's invariant structure.
(defyakugo "math" "symbolic")
(locales "x-math")
(words
  ("⊃" if)
  ("¬⊃" unless)
  ("⊃∨" elsif)
  ("⊥→" else)
  ("∎" end)
  ("≜" def)
  ("≜≜" defmacro)
  ("⌜" quote)
  ("⌞" unquote)
  ("⌞∗" unquote_splice)
  ("⊨" test)
  ("⊢" assert)
  ("λ" fn)
  ("⊕" case)
  ("⊨?" when)
  ("▷" do)
  ("⊤" true)
  ("⊥" false)
  ("∅" nil)
  ("∈" use)
  )
