; português — one surface over blue's invariant structure.
(defyakugo "pt" "português")
(locales "pt")
(words
  ("se" if)
  ("a_menos_que" unless)
  ("senao_se" elsif)
  ("senao" else)
  ("fim" end)
  ("definir" def)
  ("macro" defmacro)
  ("citar" quote)
  ("descitar" unquote)
  ("descitar_espalhar" unquote_splice)
  ("teste" test)
  ("afirmar" assert)
  ("funcao" fn)
  ("caso" case)
  ("quando" when)
  ("fazer" do)
  ("verdadeiro" true)
  ("falso" false)
  ("nulo" nil)
  ("usar" use)
  )
