; русский — one surface over blue's invariant structure.
(defyakugo "ru" "русский")
(locales "ru")
(words
  ("если" if)
  ("если_не" unless)
  ("иначе_если" elsif)
  ("иначе" else)
  ("конец" end)
  ("определить" def)
  ("макрос" defmacro)
  ("цитата" quote)
  ("расцитата" unquote)
  ("расцитата_вставка" unquote_splice)
  ("проверка" test)
  ("утверждать" assert)
  ("функция" fn)
  ("случай" case)
  ("когда" when)
  ("делать" do)
  ("истина" true)
  ("ложь" false)
  ("ничто" nil)
  ("использовать" use)
  )
