; Kiswahili — one surface over blue's invariant structure.
(defyakugo "sw" "Kiswahili")
(locales "sw")
(words
  ("kama" if)
  ("isipokuwa" unless)
  ("au_kama" elsif)
  ("vinginevyo" else)
  ("mwisho" end)
  ("fafanua" def)
  ("makro" defmacro)
  ("nukuu" quote)
  ("ondoa_nukuu" unquote)
  ("ondoa_nukuu_sambaza" unquote_splice)
  ("jaribio" test)
  ("thibitisha" assert)
  ("kazi" fn)
  ("kesi" case)
  ("wakati" when)
  ("fanya" do)
  ("kweli" true)
  ("uongo" false)
  ("tupu" nil)
  ("tumia" use)
  )
