; 中文 — one surface over blue's invariant structure.
(defyakugo "zh" "中文")
(locales "zh")
(words
  ("如果" if)
  ("除非" unless)
  ("否则如果" elsif)
  ("否则" else)
  ("结束" end)
  ("定义" def)
  ("宏定义" defmacro)
  ("引用" quote)
  ("反引用" unquote)
  ("反引用展开" unquote_splice)
  ("测试" test)
  ("断言" assert)
  ("函数" fn)
  ("情况" case)
  ("当" when)
  ("执行" do)
  ("真" true)
  ("假" false)
  ("空" nil)
  ("使用" use)
  )
